// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scritch007/go-tvdb/client/authentication"
	"github.com/scritch007/go-tvdb/client/episodes"
	"github.com/scritch007/go-tvdb/client/languages"
	"github.com/scritch007/go-tvdb/client/search"
	"github.com/scritch007/go-tvdb/client/series"
	"github.com/scritch007/go-tvdb/client/updates"
	"github.com/scritch007/go-tvdb/client/users"
)

// Default the t v d b API v2 HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new the t v d b API v2 HTTP client.
func NewHTTPClient(formats strfmt.Registry) *TheTVDBAPIV2 {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new the t v d b API v2 HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *TheTVDBAPIV2 {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new the t v d b API v2 client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *TheTVDBAPIV2 {
	cli := new(TheTVDBAPIV2)
	cli.Transport = transport

	cli.Authentication = authentication.New(transport, formats)

	cli.Episodes = episodes.New(transport, formats)

	cli.Languages = languages.New(transport, formats)

	cli.Search = search.New(transport, formats)

	cli.Series = series.New(transport, formats)

	cli.Updates = updates.New(transport, formats)

	cli.Users = users.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// TheTVDBAPIV2 is a client for the t v d b API v2
type TheTVDBAPIV2 struct {
	Authentication *authentication.Client

	Episodes *episodes.Client

	Languages *languages.Client

	Search *search.Client

	Series *series.Client

	Updates *updates.Client

	Users *users.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *TheTVDBAPIV2) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Authentication.SetTransport(transport)

	c.Episodes.SetTransport(transport)

	c.Languages.SetTransport(transport)

	c.Search.SetTransport(transport)

	c.Series.SetTransport(transport)

	c.Updates.SetTransport(transport)

	c.Users.SetTransport(transport)

}
