// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Episode episode
// swagger:model Episode

type Episode struct {

	// absolute number
	AbsoluteNumber int64 `json:"absoluteNumber,omitempty"`

	// aired episode number
	AiredEpisodeNumber int64 `json:"airedEpisodeNumber,omitempty"`

	// aired season
	AiredSeason int64 `json:"airedSeason,omitempty"`

	// airs after season
	AirsAfterSeason int64 `json:"airsAfterSeason,omitempty"`

	// airs before episode
	AirsBeforeEpisode int64 `json:"airsBeforeEpisode,omitempty"`

	// airs before season
	AirsBeforeSeason int64 `json:"airsBeforeSeason,omitempty"`

	// director
	Director string `json:"director,omitempty"`

	// directors
	Directors []string `json:"directors"`

	// dvd chapter
	DvdChapter float64 `json:"dvdChapter,omitempty"`

	// dvd discid
	DvdDiscid string `json:"dvdDiscid,omitempty"`

	// dvd episode number
	DvdEpisodeNumber float64 `json:"dvdEpisodeNumber,omitempty"`

	// dvd season
	DvdSeason int64 `json:"dvdSeason,omitempty"`

	// episode name
	EpisodeName string `json:"episodeName,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// first aired
	FirstAired string `json:"firstAired,omitempty"`

	// guest stars
	GuestStars []string `json:"guestStars"`

	// id
	ID int64 `json:"id,omitempty"`

	// imdb Id
	ImdbID string `json:"imdbId,omitempty"`

	// last updated
	LastUpdated int64 `json:"lastUpdated,omitempty"`

	// last updated by
	LastUpdatedBy string `json:"lastUpdatedBy,omitempty"`

	// overview
	Overview string `json:"overview,omitempty"`

	// production code
	ProductionCode string `json:"productionCode,omitempty"`

	// series Id
	SeriesID string `json:"seriesId,omitempty"`

	// show Url
	ShowURL string `json:"showUrl,omitempty"`

	// site rating
	SiteRating float64 `json:"siteRating,omitempty"`

	// site rating count
	SiteRatingCount int64 `json:"siteRatingCount,omitempty"`

	// thumb added
	ThumbAdded string `json:"thumbAdded,omitempty"`

	// thumb author
	ThumbAuthor int64 `json:"thumbAuthor,omitempty"`

	// thumb height
	ThumbHeight string `json:"thumbHeight,omitempty"`

	// thumb width
	ThumbWidth string `json:"thumbWidth,omitempty"`

	// writers
	Writers []string `json:"writers"`
}

/* polymorph Episode absoluteNumber false */

/* polymorph Episode airedEpisodeNumber false */

/* polymorph Episode airedSeason false */

/* polymorph Episode airsAfterSeason false */

/* polymorph Episode airsBeforeEpisode false */

/* polymorph Episode airsBeforeSeason false */

/* polymorph Episode director false */

/* polymorph Episode directors false */

/* polymorph Episode dvdChapter false */

/* polymorph Episode dvdDiscid false */

/* polymorph Episode dvdEpisodeNumber false */

/* polymorph Episode dvdSeason false */

/* polymorph Episode episodeName false */

/* polymorph Episode filename false */

/* polymorph Episode firstAired false */

/* polymorph Episode guestStars false */

/* polymorph Episode id false */

/* polymorph Episode imdbId false */

/* polymorph Episode lastUpdated false */

/* polymorph Episode lastUpdatedBy false */

/* polymorph Episode overview false */

/* polymorph Episode productionCode false */

/* polymorph Episode seriesId false */

/* polymorph Episode showUrl false */

/* polymorph Episode siteRating false */

/* polymorph Episode siteRatingCount false */

/* polymorph Episode thumbAdded false */

/* polymorph Episode thumbAuthor false */

/* polymorph Episode thumbHeight false */

/* polymorph Episode thumbWidth false */

/* polymorph Episode writers false */

// Validate validates this episode
func (m *Episode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirectors(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateGuestStars(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateWriters(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Episode) validateDirectors(formats strfmt.Registry) error {

	if swag.IsZero(m.Directors) { // not required
		return nil
	}

	return nil
}

func (m *Episode) validateGuestStars(formats strfmt.Registry) error {

	if swag.IsZero(m.GuestStars) { // not required
		return nil
	}

	return nil
}

func (m *Episode) validateWriters(formats strfmt.Registry) error {

	if swag.IsZero(m.Writers) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Episode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Episode) UnmarshalBinary(b []byte) error {
	var res Episode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
