// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// JSONErrors JSON errors
// swagger:model JSONErrors

type JSONErrors struct {

	// Invalid filters passed to route
	InvalidFilters []string `json:"invalidFilters"`

	// Invalid language or translation missing
	InvalidLanguage string `json:"invalidLanguage,omitempty"`

	// Invalid query params passed to route
	InvalidQueryParams []string `json:"invalidQueryParams"`
}

/* polymorph JSONErrors invalidFilters false */

/* polymorph JSONErrors invalidLanguage false */

/* polymorph JSONErrors invalidQueryParams false */

// Validate validates this JSON errors
func (m *JSONErrors) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvalidFilters(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateInvalidQueryParams(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JSONErrors) validateInvalidFilters(formats strfmt.Registry) error {

	if swag.IsZero(m.InvalidFilters) { // not required
		return nil
	}

	return nil
}

func (m *JSONErrors) validateInvalidQueryParams(formats strfmt.Registry) error {

	if swag.IsZero(m.InvalidQueryParams) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JSONErrors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JSONErrors) UnmarshalBinary(b []byte) error {
	var res JSONErrors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
