// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SeriesImagesQueryParams series images query params
// swagger:model SeriesImagesQueryParams

type SeriesImagesQueryParams struct {

	// data
	Data SeriesImagesQueryParamsData `json:"data"`
}

/* polymorph SeriesImagesQueryParams data false */

// Validate validates this series images query params
func (m *SeriesImagesQueryParams) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SeriesImagesQueryParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeriesImagesQueryParams) UnmarshalBinary(b []byte) error {
	var res SeriesImagesQueryParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
