// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UserRatingsDataNoLinks user ratings data no links
// swagger:model UserRatingsDataNoLinks

type UserRatingsDataNoLinks struct {

	// data
	Data UserRatingsDataNoLinksData `json:"data"`
}

/* polymorph UserRatingsDataNoLinks data false */

// Validate validates this user ratings data no links
func (m *UserRatingsDataNoLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UserRatingsDataNoLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRatingsDataNoLinks) UnmarshalBinary(b []byte) error {
	var res UserRatingsDataNoLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
