// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UserRatingsDataNoLinksEmptyArray user ratings data no links empty array
// swagger:model UserRatingsDataNoLinksEmptyArray

type UserRatingsDataNoLinksEmptyArray struct {

	// data
	Data []interface{} `json:"data"`
}

/* polymorph UserRatingsDataNoLinksEmptyArray data false */

// Validate validates this user ratings data no links empty array
func (m *UserRatingsDataNoLinksEmptyArray) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserRatingsDataNoLinksEmptyArray) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserRatingsDataNoLinksEmptyArray) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRatingsDataNoLinksEmptyArray) UnmarshalBinary(b []byte) error {
	var res UserRatingsDataNoLinksEmptyArray
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
